### PR TITLE
Fix markdown in some files for better readability

### LINKED ISSUE #56: Improper formatting of some files
Some of these files seem really rushed and aren't formatted properly (either not proper Markdown or not a Markdown file at all) making it hard for some users to read. 

Examples:
https://github.com/avsingh999/Ruby-for-Beginner/blob/master/Functions-in-Ruby
https://github.com/avsingh999/Ruby-for-Beginner/blob/master/Array_in_Ruby.md
https://github.com/avsingh999/Ruby-for-Beginner/blob/master/Block_in_Ruby.md
https://github.com/avsingh999/Ruby-for-Beginner/blob/master/How%20to%20find%20index%20of%20element%20in%20array%20ruby.md

### PR DESCRIPTION
**Pull request by luhova**
Fixes #56

#### What does this PR do?

[Improper formatting of some files](#56 )

#### Summary of the changes
Using some markdown code blocks for better readability.
#### Things done:
 *
 *

### CODE REVIEW

**Comment by avsingh999** [comment]
@luhova  great work you can do this with other files
thanks :)

**Comment by avsingh999** [comment]
@luhova  please resolve conflicts
 thank you:)

**Comment by luhova** [comment]
@avsingh999 I just saw that all of the files I have formatted are already fixed in master. I guess you can close my PR?

**Comment by avsingh999** [comment]
@luhova ok no mention
thanks :)

**Pull request closed without merging**
